version: '3.9'

services:
  # --------------------------
  # Laravel Application Service
  # --------------------------
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: hostel_app
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
    networks:
      - hostel_network

  # --------------------------
  # MySQL Database
  # --------------------------
  mysql:
    image: mysql:8.0
    container_name: hostel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hostel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hostel_network

  # --------------------------
  # Nginx Web Server
  # --------------------------
  nginx:
    image: nginx:latest
    container_name: hostel_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hostel_network

# --------------------------
# Networks & Volumes
# --------------------------
networks:
  hostel_network:

volumes:
  mysql_data:
